#!/usr/bin/env python
import SlideShow

config = SlideShow.Config()
config.parse_argv()
SlideShow.check_system(config)

if config["gui"]:
    import SlideShow.pygtk
    import pygtk
    pygtk.require("2.0")
    import gtk
    app = SlideShow.pygtk.SlideShowApp(config)
    gtk.main()
else:
    import logging
    logging.basicConfig(level=logging.WARN)

    if not(config["input_txtfile"]):
        raise Exception("No input file specified")

    pipeline = SlideShow.read_pipeline(config["input_txtfile"], config)
    progress = SlideShow.Progress()
    SlideShow.initialize_pipeline(pipeline, config)
    SlideShow.build(pipeline, config, progress)
    
